# Generated by Django 4.1.5 on 2023-01-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fields_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='location',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='meata_details',
            field=models.TextField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FieldImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fields_Management.field')),
            ],
        ),
    ]
